language: node_js
install:
  - npm install
  - npm install --save history@3.3.0
  - npm install --save react-router@3.2.0
  - npm install --save antd@2.13.10
script:
  - npm run build
node_js:
  - lts/*
cache:
  directories:
    - node_modules
